=== jesseeichar/debrief/tags/eclipse_37/org.mwc.debrief.help/cheat_sheets/compositeContentFile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Schema file written by PDE -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation>
         The schema definition for a composite cheat sheet content file. A composite cheat sheet consists of a set of tasks organized into task groups. Each task can be a simple cheat sheet or a user contributed task kind.
      </xsd:documentation>
	</xsd:annotation>
	<xsd:element name="compositeCheatsheet">
		<xsd:annotation>
			<xsd:documentation>
            The root element of a composite cheatsheet
         </xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:choice>
				<xsd:element ref="taskGroup"/>
				<xsd:element ref="task"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
                  The name of the composite cheat sheet which will be displayed in large font when the composite cheat sheet is opened.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="taskGroup">
		<xsd:annotation>
			<xsd:documentation>
            A task group represents a collection of related tasks. If the kind is &quot;choice&quot; only one of the child tasks need to be completed. If the kind is &quot;set&quot; or &quot;sequence&quot; all children must be completed.
         </xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:choice>
					<xsd:element ref="task"/>
					<xsd:element ref="taskGroup"/>
				</xsd:choice>
				<xsd:element ref="intro" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="onCompletion" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="dependency" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="kind" type="xsd:string" use="optional" default="set">
				<xsd:annotation>
					<xsd:documentation>
                  The kind of this task group which can be &quot;set&quot;, &quot;sequence&quot; or &quot;choice&quot;. If the kind is set or sequence this task group is complete when all of its child tasks/task groups have been completed. In addition the subtasks of a sequence must be completed in order. A choice is complete when any of its subtasks has been completed.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="name" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
                  The name of this task group which will be displayed in the task explorer.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="id" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
                  An id for this task group which is required if this task group is referenced by a dependency element.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="skip" type="xsd:boolean" use="optional" default="false">
				<xsd:annotation>
					<xsd:documentation>
                  If true this group of tasks may be skipped.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="task">
		<xsd:annotation>
			<xsd:documentation>
            A leaf task within a composite cheat sheet. A task does not have children, but it does have a task editor which shows in the lower/right hand pane of the cheat sheet view. The task kind determines which task editor will be opened, a task kind of &quot;cheatsheet&quot; represents a simple cheatsheet. Other task kinds may be contributed.
         </xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="intro" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="onCompletion" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="dependency" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="kind" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
                  The task kind. A task kind of &quot;cheatsheet&quot; represents a simple cheatsheet, other task kinds can be contributed using the extension point org.eclipse.ui.cheatsheets.cheatSheetContent.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="name" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
                  The name of this task which will be displayed in the task explorer.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="id" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
                  An id for this task group which is required if this task group is referenced by a dependency element.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="skip" type="xsd:boolean" use="optional" default="false">
				<xsd:annotation>
					<xsd:documentation>
                  If true this task may be skipped.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="param">
		<xsd:annotation>
			<xsd:documentation>
            A parameter to a task within a composite cheatsheet. Each parameter has a name and value, both of which are strings. A task may have any number of parameters, two parameters for a single task may not share the same name.
         </xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
                  The name of this parameter.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="value" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
                  The value of this parameter.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="intro" type="xsd:string">
		<xsd:annotation>
			<xsd:documentation>
            Contains the text which will be displayed before this task has been started. May contain form text markup.
         </xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="onCompletion" type="xsd:string">
		<xsd:annotation>
			<xsd:documentation>
            Contains the text which will be displayed in the completion panel for this task. May contain form text markup.
         </xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="dependency">
		<xsd:annotation>
			<xsd:documentation>
            Creates a dependency between two tasks or subtasks.
         </xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:attribute name="task" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
                  The id of the task or task group which must be completed before this task can be started.
               </xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:annotation>
		<xsd:documentation>
         3.2
      </xsd:documentation>
	</xsd:annotation>
	<xsd:annotation>
		<xsd:documentation>
         
      </xsd:documentation>
	</xsd:annotation>
	<xsd:annotation>
		<xsd:documentation>
         
      </xsd:documentation>
	</xsd:annotation>
	<xsd:annotation>
		<xsd:documentation>
         
      </xsd:documentation>
	</xsd:annotation>
	<xsd:annotation>
		<xsd:documentation>
         Copyright (c) 2006 IBM Corporation and others.&lt;br&gt;
All rights reserved. This program and the accompanying materials are made 
available under the terms of the Eclipse Public License v1.0 which accompanies 
this distribution, and is available at &lt;a href=&quot;http://www.eclipse.org/legal/epl-v10.html&quot;&gt;http://www.eclipse.org/legal/epl-v10.html&lt;/a&gt;
      </xsd:documentation>
	</xsd:annotation>
</xsd:schema>

=== jesseeichar/debrief/tags/eclipse_342/org.mwc.debrief.help/cheat_sheets/GettingStarted/GettingStartedComposite.xml
<?xml version="1.0" encoding="UTF-8"?>
<compositeCheatsheet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../compositeContentFile.xsd" name="Getting some data into Debrief NG">
	<taskGroup name="Getting started with Debrief NG">
		<taskGroup name="Defining your workspace" kind="sequence">
			<task kind="cheatsheet" name="Generating a project">
				<intro>Right, we'll start off by creating a Project that will contain our work</intro>
				<onCompletion>You've now created a project into which you can store your Debrief data</onCompletion>
				<param name="id" value="org.mwc.debrief.help.started.generate_project"/>
				<param name="showIntro" value="true"/>
			</task>
			<task kind="cheatsheet" name="Finding your data">
				<intro>If you already have one or more folders containing Debrief data, you can add them to your Debrief NG project (or load sample data that was installed within Debrief NG)</intro>
				<onCompletion>You can now repeat this process to create links to your other Debrief data directories.</onCompletion>
				<param name="id" value="org.mwc.debrief.help.started.existing_data"/>
			</task>
			<intro>In comparison with prior versions of Debrief, Debrief NG introduces the concept of a Workspace - a central repository for your assorted analysis-related documents.  Within this workspace your work is grouped into individual projects: thus you can quickly switch between concurrent analysis tasks.  Debrief's provision of projects alows you to quickly drag and drop Debrief data-files and plots.</intro>
			<onCompletion>Right, Debrief now knows where to find your data.  In the next series of steps you will load and examine some data.</onCompletion>
		</taskGroup>
		<taskGroup name="Viewing some data" kind="sequence">
			<task kind="cheatsheet" name="Creating a new plot">
				<intro>We will now use Debrief's New Plot wizard to create a plot ready for import of data-files.</intro>
				<onCompletion>Note that we didn't have to use the wizard steps, we could have inserted chart features into our Plot by hand using the Chart Features menu.  </onCompletion>
				<param name="id" value="org.mwc.debrief.help.started.create_plot"/>
			</task>
			<task kind="cheatsheet" name="Importing some existing data">
				<intro>Debrief NG stores it's user data in collections named projects.</intro>
				<param name="id" value="org.mwc.debrief.help.started.loading_data"/>
			</task>
			<intro>This series of steps will guide you through creating then populating a new Debrief plot.</intro>
		</taskGroup>
		<intro>This series of cheatsheets will guide you through creating your Debrief working environment, customising it according to your preferred file locations, and loading some analysis data.</intro>
	</taskGroup>
</compositeCheatsheet>
