=== jesseeichar/debrief/branches/try_ganymede/org.mwc.debrief.help/cheat_sheets/contentFile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
		Schema for cheat sheet content file.
 		Copyright (c) 2004, 2005 IBM Corporation and others.&lt;br&gt;
		All rights reserved. This program and the accompanying materials are made 
		available under the terms of the Eclipse Public License v1.0 which 
		accompanies this distribution, and is available at 
		&lt;a href=&quot;http://www.eclipse.org/legal/epl-v10.html&quot;&gt;http://www.eclipse.org/legal/epl-v10.html&lt;/a&gt;
		</xsd:documentation>
	</xsd:annotation>
	<xsd:element name="cheatsheet">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="intro"/>
				<xsd:element ref="item" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="title" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="intro">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description"/>
			</xsd:sequence>
			<xsd:attribute name="contextId" type="xsd:string" use="optional"/>
			<xsd:attribute name="href" type="xsd:string" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="description">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string"/>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="onCompletion">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string"/>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="item">
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:sequence>
					<xsd:element ref="description"/>
					<xsd:choice minOccurs="0">
						<xsd:element ref="action"/>
						<xsd:element ref="command"/>
						<xsd:element ref="perform-when"/>
					</xsd:choice>
					<xsd:element ref="onCompletion" minOccurs="0"/>
				</xsd:sequence>
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:element ref="subitem"/>
					<xsd:element ref="conditional-subitem"/>
					<xsd:element ref="repeated-subitem"/>
				</xsd:choice>
			</xsd:choice>
			<xsd:attribute name="title" type="xsd:string" use="required"/>
			<xsd:attribute name="dialog" type="xsd:boolean" use="optional" default="false"/>
			<xsd:attribute name="skip" type="xsd:boolean" use="optional" default="false"/>
			<xsd:attribute name="contextId" type="xsd:string" use="optional"/>
			<xsd:attribute name="href" type="xsd:string" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="subitem">
		<xsd:complexType>
			<xsd:choice minOccurs="0">
				<xsd:element ref="action"/>
				<xsd:element ref="command"/>
				<xsd:element ref="perform-when"/>
			</xsd:choice>
			<xsd:attribute name="label" type="xsd:string" use="required"/>
			<xsd:attribute name="kind" type="xsd:string" use="required"/>
			<xsd:attribute name="skip" type="xsd:boolean" use="optional" default="false"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="conditional-subitem">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="subitem" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="condition" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="repeated-subitem">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="subitem"/>
			</xsd:sequence>
			<xsd:attribute name="values" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="action">
		<xsd:complexType>
			<xsd:attribute name="when" type="xsd:string" use="optional"/>
			<xsd:attribute name="confirm" type="xsd:boolean" use="optional" default="false"/>
			<xsd:attribute name="class" type="xsd:string" use="optional"/>
			<xsd:attribute name="pluginId" type="xsd:string" use="optional"/>
			<xsd:attribute name="param1" type="xsd:string" use="optional"/>
			<xsd:attribute name="param2" type="xsd:string" use="optional"/>
			<xsd:attribute name="param3" type="xsd:string" use="optional"/>
			<xsd:attribute name="param4" type="xsd:string" use="optional"/>
			<xsd:attribute name="param5" type="xsd:string" use="optional"/>
			<xsd:attribute name="param6" type="xsd:string" use="optional"/>
			<xsd:attribute name="param7" type="xsd:string" use="optional"/>
			<xsd:attribute name="param8" type="xsd:string" use="optional"/>
			<xsd:attribute name="param9" type="xsd:string" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="command">
		<xsd:complexType>
			<xsd:attribute name="when" type="xsd:string" use="required"/>
			<xsd:attribute name="confirm" type="xsd:boolean" use="optional" default="false"/>
			<xsd:attribute name="serialization" type="xsd:string" use="optional"/>
			<xsd:attribute name="returns" type="xsd:string" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="perform-when">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:choice maxOccurs="unbounded">
					<xsd:element ref="action"/>
					<xsd:element ref="command"/>
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="condition" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== jesseeichar/debrief/trunk/org.mwc.debrief.help/cheat_sheets/GettingStarted/EditingYourData.xml
<?xml version="1.0" encoding="UTF-8"?>
<cheatsheet title="Editing your data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\contentFile.xsd">
	<intro>
		<description>So, you've found your data, loaded it into Debrief, and now you want to make some changes to it.  This cheat-sheet will give you some pointers.</description>
	</intro>
	<item title="Check you have some data" href="/org.eclipse.platform.doc.user/concepts/cnav.htm">
		<description>In the top left hand corner of Debrief you should find the Navigator window.  If is isn't there, select "Navigator" from Debrief's Window/Show View menu.  Also check you have our sample data-files - it they're not there, find how to load them from the "Loading sample data" cheat-sheet.</description>
	</item>
	<item title="Open the sample plot-file">
		<description>If it&apos;s not already open, double-click on &apos;sample.xml&apos; in the Navigator window, and the sample plot will open.</description>
	</item>
	<item
       href="/org.mwc.debrief.help/html/legacy/moving_around.html"
       title="Fit to window">
		<description>To make sure all of the data is visible, click on the &quot;Fit-to-Window&quot; toolbar button.  Read more about the toolbar buttons by clicking on the help-link to the right of this text.</description>
	</item>
 <item
       title="View a the data in tree form">
    <description>
       In addition to viewing your data on the 2D plot, the <b>Layer Manager</b> displays it in tree form.  Switch to the <b>Layer Manager</b> view to see the data.  You&apos;ll see the two tracks there, together with other layers that contain <b>Chart Features</b> (such as the <b>Grid</b> and <b>Scale</b>), and the <b>Misc</b> layer that contains graphical annotations.
    </description>
 </item>
	<item title="Make sure the properties window is open" href="/org.eclipse.platform.doc.user/concepts/cpropview.htm">
		<description>The properties window is normally at the bottom left of Debrief.  If it's there but not at the top of the 'stack', click on its title to reveal it.  If you can't find it, select "Properties" from the 'Window/Show View" drop-down list.</description>
	</item>
	<item title="Select an item">
		<description>Now double-click on one of the corners of the green rectangle near the centre of the track plot.  You&apos;ll now see its editable attributes appear on the properties window.  Cool.  You&apos;ll see that the attributes are grouped for ease of use, and some must be expanded (those for location &amp; time).</description>
	</item>
	<item title="Make a change">
		<description>Now have a go at changing the rectangle's label color.  Click once on the green rectangle next to 'LabelColor'.  A button containing three dots will appear.  Click on this to open the color editor.  Click on the red rectangle and then the 'OK' button.  The dialog will close, the label color property will be updated, and the plot will redraw.  Well done.</description>
	</item>
	<item title="Undo the change">
		<description>Oops, it appears we shouldn't have changed the label color, it doesn't meet NATO MilStd 12332 Sub-para 14g (2002 version).  To undo a change, first click on the tab at the top of the sample.xml plot (to tell Debrief which plot we're undoing).  Now click on the Edit menu, and select Undo (it's the first item).  The color of the label will now change back.  Look on the Edit menu again, and you'll see there's now a "Redo" command available - just in case you're undecided about your adherence to sub-para 14g.  Note, it's not just edits that are undo-able, lots of operations can be undone, just have a look on the Edit menu whenever you feel the need to step-back.  If you think something isn't on there but it should be, just ask...</description>
	</item>
	<item title="Edit a position">
		<description>To select a position within a track, just double-click on it - its editable attributes will appear in the properties window.  You can now change the symbol, label, or track color for that position.</description>
	</item>
	<item title="Edit a whole track">
		<description>Aaah, but how do you edit a track?  Easy, just use the Layer Manager to select it rather than clicking on the plot.  Open the Layer Manager (or select Layer Manager from the Window/Show View drop-down menu).  In the Layer Manager click once on the name of a track, and the whole track's properties will be editable in the Properties View.  The Layer Manager is also useful for selecting non-geographic entities (such as a grid, scale, or background data-set) to be edited.</description>
	</item>
	<item title="Edit directly from the plot itself">
		<description>For some attributes, you don't even need to use the Properties View.  Just right-click on an item on your plot.  The popup menu shows a series of options and commands.  A drop-down menu is shown next to the current item's name.  From this drop-down menu you'll be able to edit all of the item's true/false or 'select one from many' attributes.  Note, if you click on a vehicle position, a drop-down is shown for the parent track as well as the position itself.  Also note, that the right-click menu is shown if you click on an item from the Layer Manager.</description>
	</item>
	<item title="Don't forget to save">
		<description>Now that you've invested all that effort in your plot, don't forget to save it.  Just click on the floppy-disk icon on the main toolbar.  If the data you're looking is actually an REP file, you will be invited to save the file in Debrief's XML plot-file format - since REPs can't store formatting data.</description>
	</item>
</cheatsheet>

=== jesseeichar/debrief/tags/eclipse_342/org.mwc.debrief.help/cheat_sheets/sensor/LoadingSensorData.xml
<?xml version="1.0" encoding="UTF-8"?>
<cheatsheet title="Filtering your view" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\contentFile.xsd">
	<intro>
		<description>With ever-increasing data rates from multiple recording systems it is easy for an analysis plot to become swamped.  Debrief NG provides tools to reduce the volume and type of data displayed.  This tutorial will lead you through the management of large volumes of data.</description>
	</intro>
	<item title="Check you have some data">
		<description>In the top left hand corner of Debrief you should find the Navigator window.  If is isn't there, select "Navigator" from Debrief's Window/Show View menu.</description>
		<action class="OpenCheatSheetAction" param1=""/>
	</item>
	<item title="Check you have a workspace">
		<description>Before you can link in existing data, you need to define a project for your work.  This is a parent folder within which your links are stored.  If your Navigator window is empty, you must follow the "Generating a project" cheat-sheet accessed from the Help/Cheat Sheets menu.</description>
	</item>
	<item title="Add a new Folder">
		<description>Right-click on your current project in the Navigator view, then select 'Folder' from the 'New' sub-menu.  The New Folder wizard will open.
		</description>
	</item>
	<item title="Show the Advanced options">
		<description>Still in the New Folder Wizard, click the 'Advanced' button to display the Advanced options.</description>
	</item>
	<item title="Linking to an existing folder">
		<description>Click on the 'Link to folder in the file system', and navigate to the target folder</description>
	</item>
	<item title="Done">
		<description>Well done, there you are.  Just repeat this process to add any other data directories you want to load data from.</description>
	</item>
</cheatsheet>

=== jesseeichar/debrief/branches/eclipse_34/org.mwc.debrief.help/cheat_sheets/narratives/PreparingNarrativeData.xml
<?xml version="1.0" encoding="UTF-8"?>
<cheatsheet title="Preparing narrative data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\contentFile.xsd">
	<intro>
		<description>In addition to geospatial data, Debrief can analyse narrative data in the form of time-stamped narrative comments.  The comments may originatr from a number of sources, but ultimately they must be stored in columns in a textual REP file.</description>
	</intro>
	<item title="Check you have some data">
		<description>In the top left hand corner of Debrief you should find the Navigator window.  If is isn't there, select "Navigator" from Debrief's Window/Show View menu.</description>
	</item>
	<item title="Check you have a workspace">
		<description>Before you can link in existing data, you need to define a project for your work.  This is a parent folder within which your links are stored.  If your Navigator window is empty, you must follow the "Generating a project" cheat-sheet accessed from the Help/Cheat Sheets menu.</description>
	</item>
	<item title="Add a new Folder">
		<description>Right-click on your current project in the Navigator view, then select 'Folder' from the 'New' sub-menu.  The New Folder wizard will open.
		</description>
	</item>
	<item title="Show the Advanced options">
		<description>Still in the New Folder Wizard, click the 'Advanced' button to display the Advanced options.</description>
	</item>
	<item title="Linking to an existing folder">
		<description>Click on the 'Link to folder in the file system', and navigate to the target folder</description>
	</item>
	<item title="Done">
		<description>Well done, there you are.  Just repeat this process to add any other data directories you want to load data from.</description>
	</item>
</cheatsheet>
